### PR TITLE
Fully Localized Files

### PR DESCRIPTION
**Pull request by nkh0472**
No more CDN needed.

### CODE REVIEW

**Comment by nkh0472** [comment]
Updated dependences & necessary fix for deprecated functions.

**Comment by NeverBehave** [comment]
Please resolve conflit and we could do the merge

**Comment by nkh0472** [comment]
The conflicted file is replaced by mikutap.js in https://github.com/HFIProgramming/mikutap/pull/18.
Thus it can be safely deleted.

**Comment by nkh0472** [comment]
Meanwhile, https://github.com/HFIProgramming/mikutap/pull/15 can be closed because no more CDN is needed.

**Pull request merged**
